### ISSUE TITLE
Trouble with Templater code

### ISSUE THREAD

**Issue by menagerie198** [Yaozhuwa/easy-typing-obsidian#7]
Hi - I love the 'Easy Type' plugin, but it is causing me this one headache - in 'Templater' scripts, eg., the 'f' and the 'c' in the following - <% tp.file.cursor() %> - keep getting capitalised and a space inserted ('<% tp. File. Cursor() %>'). This causes my templates to error out. Is there an existing way to avoid this?

**Comment by Yaozhuwa** [comment]
Now, you can press the hot key `Ctrl+Tab` to turn off the autoformat when you are editting your template notes.
In few days, this plugin will support user defined regular expression to ignore the match. That will solve your problem. But now, because of my negligence, I update my plugin(v3.2.0) with a broken feature of regular expression. Don't use it. I will fix it in few days.

**Comment by menagerie198** [comment]
Thank you very much. Loving your work!

**Comment by Yaozhuwa** [comment]
In v3.2.2, you can turn on the User defined RegExp Switch, and add `<%.*?%>` to the textarea below.
![image](https://user-images.githubusercontent.com/28787183/122103687-7a04c700-ce49-11eb-91d8-d1ee784c7203.png)
After that, the plugin will ignore the content in `<%some-content%>`.
